### ISSUE TITLE
Neptune 4 series compatibility

### ISSUE THREAD

**Issue by luisillo26** [TheJMaster28/ElegooNeptuneThumbnailPrusa#1] opened 2023-08-15 20:44 UTC
Hi, I'd like to test this script for the new Neptune 4 series but I noticed it's an exe, any chance that you can make it work directly from the python code so I can test in my mac?

**Comment by TheJMaster28** [comment] 2023-08-16 01:14
Yes you can! You need to pull down the repo, make sure you install requirements.txt, and in PrusaSlicer Post-Porcessing Scripts, have the path to python and the path to the thumbnail.py script. Then it should the script. Let me know if it works on the Neptune 4 printers so that I can update the compatible printers!

**Comment by luisillo26** [comment] 2023-08-17 03:58
It doesn't look like it's working, I figured out how to execute the script from PS but the thumbnail embedded in the gcode is not recognized by the printer. I'm attaching the gcode file.
[Shape-Box_0.2mm_PLA_N4P.gcode.zip](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/files/12365348/Shape-Box_0.2mm_PLA_N4P.gcode.zip)


This is the way I'm invoking from PS:
`/opt/homebrew/bin/python3 /tmp/ElegooNeptuneThumbnailPrusa/thumbnail.py`

**Comment by TheJMaster28** [comment] 2023-08-17 04:37
hmmm, looks like it's not running the script. I am not seeing the g code it's supposed to add at the beginning of the file with what you provided. Here's how I run it in PS in Windows:
`"C:\Program Files\Python311\python.exe" "D:\Documents\Projects\ElegooNeptuneThumbnailPrusa\thumbnail.py";`

There should also be an app.log where the script is that should be generated when it runs. 

You can also try and run the script manually after the gcode file is created. You would just add the path to the gcode file as an argument to the script.

**Comment by luisillo26** [comment] 2023-08-17 17:20
I found the issue, libColPic.dylib needs to be compiled for Apple silicon.
Any chance we could get that file for M1 macs?

```
2023-08-17 10:52:25,862 - ERROR - Error occurred while running application.
Traceback (most recent call last):
  File "/tmp/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 167, in <module>
    obj.run()
  File "/tmp/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 141, in run
    new_thumbnail_gcode += self.parse_screenshot_new(prusa_thumbnail_decoded, 200, 200, ";gimage:")
  File "/tmp/ElegooNeptuneThumbnailPrusa/thumbnail.py", line 73, in parse_screenshot_new
    p_dll = CDLL(dll_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/tmp/ElegooNeptuneThumbnailPrusa/libColPic.dylib, 0x0006): tried: '/tmp/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/tmp/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (no such file), '/tmp/ElegooNeptuneThumbnailPrusa/libColPic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

**Comment by luisillo26** [comment] 2023-08-17 20:06
I made it work by setting an x86_64 virtual environment using miniconda. Unfortunately the thumbnail generated is not recognized by the Neptune 4 Pro display.

![pic](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/assets/1028540/988c3f99-dd6e-4c05-84aa-0eea0696f04c)



From PrusaSlicer:
/Users/user/miniconda3/envs/my_x86_env/bin/python3 /tmp/ElegooNeptuneThumbnailPrusa/thumbnail.py

[Shape-Box_0.2mm_PLA_N4P.gcode.zip](https://github.com/TheJMaster28/ElegooNeptuneThumbnailPrusa/files/12373187/Shape-Box_0.2mm_PLA_N4P.gcode.zip)

**Comment by TheJMaster28** [comment] 2023-08-18 06:40
I looked at Elegoo's Cura source code to see what they added for the 4 series printers and it is still using the same dlls as the 3 series. I notice that your gcode file has multiple thumbnails for PS. You can try and changing the G-code thumbnails setting to be only `200x200`
and see if that works, but it should have still rendered the image. 

You could also verify that gcode from Elegoo's Cura renders the image. It could be a bug on their end.

**Comment by guneremre** [comment] 2023-08-19 05:55
unfortunately i can confirm that thumbnail is not generated on 4 pro..
and there is no errors on log file.

**Comment by TheJMaster28** [comment] 2023-09-12 04:41
I made a new release if you guys want to try that. 

Also, if you guys could also try and use Klipper thumbnail settings, `32x32, 300x300` in PrusaSlicer G-code thumbnails setting, and in the script for arguments put `"--img_size" "300x300"` and see if that works.

**Comment by bread1919** [comment] 2023-09-18 14:48
I tried adding the additional arguments. However, nothing changed on my Neptune 4 pro, still no thumbnails.

**Comment by TheJMaster28** [comment] 2023-10-03 07:49
I pushed a new release that might hopefully work on the 4 series printers. If not, let me know!

**Comment by fifonik** [comment] 2023-10-03 14:12
Thanks for your effort to make it work.

I've just tried the version 2.0.0 and no luck -- the thumbnail does not show up on Neptune 4 screen.
app.log:
```
2023-10-04 00:00:59,718 - INFO - gcode input file from slicer: C:\Users\[USER]\AppData\Local\Temp\.1976.gcode.pp
2023-10-04 00:00:59,719 - DEBUG - found thumbnail begin at file line: 4
2023-10-04 00:00:59,719 - DEBUG - found thumbnail end at file line: 453
2023-10-04 00:00:59,719 - DEBUG - Decoding thumbnail from base64
2023-10-04 00:01:00,188 - DEBUG - Writing text to image
2023-10-04 00:01:00,224 - DEBUG - using Windows dll: C:\Users\[USER]\AppData\Local\Temp\_MEI5802\ColPic_X64.dll
2023-10-04 00:01:00,259 - DEBUG - using Windows dll: C:\Users\[USER]\AppData\Local\Temp\_MEI5802\ColPic_X64.dll
2023-10-04 00:01:00,283 - DEBUG - Parsed new thumbnail screenshot gcode.
2023-10-04 00:01:00,675 - INFO - Wrote new thumbnail screenshot in gcode file: C:\Users\[USER]\AppData\Local\Temp\.1976.gcode.pp
```

Checked input file (mentioned in log as **.1976.gcode.pp**) -- one base64 encoded image.
Checked output file: 31 entries of "gimage:" and 21 entries of ";simage" + original thumbnail entry.

Un-commented `qimage.save(path.join(script_dir, "test.png"))` and file test.png was saved correctly.

**Comment by TheJMaster28** [comment] 2023-10-04 05:24
There was a typo in there that I fixed right now and release v2.0.1 if you want to try that. I believe that adding `Cura_SteamEngine X.X` in the gcode file should make it think its a Cura output.

**Comment by fifonik** [comment] 2023-10-04 06:06
Thanks. I will try it later today and report back.

**Comment by fifonik** [comment] 2023-10-04 09:00
2.0.1 still does not display thumbnail.
I checked Molodos's code mentioned in your source and noticed that he is also masking 'PrusaSlicer' origin.
I've manually modified gcode file created by your program (2.0.1) and replaced `generated by PrusaSlicer 2.6.1` with `generated by Censored 2.6.1`. After that my Neptune 4 shows the thumbnail with no issues.

In addition, I've manually deleted base64-encoded image from gcode file (to reduce file size) and it still works.

So could you please made changes to mask PrusaSlicer.
Also, it would be nice if you add a new option that can be used to remove the base64 image.
Finally, could you add in description information about hiding the console window. Google suggests that it can be done by calling `c:\path\to\pythonw.exe c:\path\to\thumbnail.py` (pyton**w**.exe instead of python.exe)

Ta

UPDATE: I tried different masking options for PrusaSlicer. Works with **CensoredSlicer**, **Prusa-Slicer**, **P-rusaSlicer**. Does not wotk with **ThePrusaSlicer**. I'd stick with **Prusa-Slicer**.

So this is a tiny patch to your 2.0.1 that works wor me:
```
- file_content_new = new_thumbnail_gcode + file_content
+ file_content_new = new_thumbnail_gcode + file_content.replace("PrusaSlicer", "Prusa-Slicer")

```

**Comment by TheJMaster28** [comment] 2023-10-05 05:23
Ok add the fix for it in v2.0.2 release. I'll work on the other features later. Thanks for all your guys help!

**Closed as completed by TheJMaster28** 2023-10-05 05:23 UTC

**Comment by fifonik** [comment] 2023-10-05 08:47
> I'll work on the other features later. 

I've already implemented something I suggested locally.
Would you like to receive the changed file or you do dot care about other stuff?

**Comment by TheJMaster28** [comment] 2023-10-05 19:04
If you want to, you can make a pull request so that it can get into the code base. Then I can do another release and that way you'll get credit for the changes

**Comment by fifonik** [comment] 2023-10-07 06:59
It turned out that I want too many things to be changed so I just forked it. Sorry.
